language: objective-c
osx_image: xcode8.3

env: 
  global:
  - FRAMEWORK_NAME=MXSegmentedPager

before_install:
- brew update
- brew outdated carthage || brew upgrade carthage

install:
- gem install cocoapods
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

before_script:
- carthage bootstrap

script:
- set -o pipefail && xcodebuild -project MXSegmentedPager.xcodeproj -scheme $FRAMEWORK_NAME -sdk iphonesimulator10.3 -configuration Release | xcpretty -c
- pod lib lint --quick

before_deploy:
- carthage build --no-skip-current
- carthage archive $FRAMEWORK_NAME

deploy:
  provider: releases
  api_key:
    secure: uimE5l184d6Lg1eRXfSaGUXXdeajVuICeHTyIuxZzYb105Bp1e2zPB5SgLOY21WL1OHV+T5TxtTfw+O1sNuoEmt/x2YcVqmfqOuBc+6IEKgrqVtHP0ADN+YLvIvDSx3y4pG9rrZB2UT0OR9ZXPmaQpnbMbxLZrtf5OFoIC2WilY=
  file: $FRAMEWORK_NAME.framework.zip
  skip_cleanup: true
  on:
    repo: maxep/MXSegmentedPager
    tags: true
